/**
 * Created by sn on 2019/3/25.
 */

const constants = {
  CODE_ERROR: -1,
  CODE_SUCCESS: 200,
  CODE_NOT_FOUND: 404,
  CODE_HAS_LOGIN: 40000,
  CODE_NOT_LOGIN: 40001,
  CODE_LIMIT_LOGIN: 40002,
  CODE_DENIED: 40003,
  CODE_ILLEGAL: 40004,
  CODE_PARAMS_REQUIRED: 41001,
  CODE_PARAMS_ILLEGAL: 41002,
  CODE_UPLOAD_SUCCESS: 50000,
  CODE_UPLOAD_ERROR: 50001,

  MSG_ERROR: '系统繁忙',
  MSG_SUCCESS: '请求成功',
  MSG_NOT_FOUND: '接口不存在',
  MSG_HAS_LOGIN: '账号已登录',
  MSG_NOT_LOGIN: '账号尚未登录',
  MSG_LIMIT_LOGIN: '账号已被禁',
  MSG_DENIED: '权限不足',
  MSG_ILLEGAL: '操作非法',
  MSG_PARAMS_REQUIRED: '参数为空',
  MSG_PARAMS_ILLEGAL: '参数非法',
  MSG_UPLOAD_SUCCESS: '上传成功',
  MSG_UPLOAD_ERROR: '上传失败',
}

export default constants
